<a href="https://colab.research.google.com/github/Ayushi12578/davis_training/blob/main/Numpy%20library(20-04-2026).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
pip install numpy


In [8]:
import numpy as np
x = np.arange(10,100,5)
print(x)


[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
#array creation in numpy
array3= np.zeros((5,3))
print(array3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
arr= np.zeros((4,5),dtype ='int')
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [13]:
array = np.zeros((3,6,2),dtype='int')
print(array)

[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]


Replace `your_library_name` with the actual name of the library you want to install. For example, to install `pandas`, you would use `pip install pandas`.