<a href="https://colab.research.google.com/github/Ayushi12578/davis_training/blob/main/Numpy%20library(20-04-2026).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
pip install numpy


In [8]:
import numpy as np
x = np.arange(10,100,5)
print(x)


[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
#array creation in numpy
array3= np.zeros((5,3))
print(array3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
arr= np.zeros((4,5),dtype ='int')
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [13]:
array = np.zeros((3,6,2),dtype='int')
print(array)

[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]


In [14]:
# ones array
a =np.ones((4,3))
print(a)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
b=np.ones((2,5,1))
print(b)

[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]]


In [24]:
def get_even_factors(num):
    factors = []
    for i in range(1, int(num**0.5) + 1):
        if num % i == 0:
            if i % 2 == 0:
                factors.append(i)
            if (num // i) % 2 == 0 and (num // i) != i:
                factors.append(num // i)
    factors.sort()
    return factors

given_number = 30
list_even_factors = get_even_factors(given_number)
array = np.array(list_even_factors)

print(f"Given number: {given_number}, Even factors: {list_even_factors}")
print(array)

Given number: 30, Even factors: [2, 6, 10, 30]
[ 2  6 10 30]


In [25]:
import requests
url ="https://raw.githubusercontent.com/Ayushi12578/davis_training/refs/heads/main/Class%20work/data%20analitics%20note.txt"
response = requests.get(url)
data= response.text
print(data)

                                                  DATA ANALITICS


PROJECT
1 MILLION ->DATA SET
IN PYTHIN
LIB   ----------->
  MATPLOTLIB
NUMPY
PANDAS

DASBOARD
POWER BI
LOOKER STUDIO
APPSCRIPT

SELECTION STATEMENT
IF
IF--ELSE
NESTED-IF--ELSE
IF--ELIF--ELSE

ITERATION

Best Example is ----> Ringing Alarm
To repeat same task until condition become false
Component
Initilization :- start
Condition :-
Update :-
Loop in python
While Loop :- when number of term are not given
For loop :- When number of term are given
Range()
To generate sequence of number in given range
it is memory efficient (Generate number one by one when needed) Syntax:- variable= range(Start,end,step)
  strat ---> beginning value(default value is 0)
end---> if the last value (excluded)
stop --->gap btw two number
 
Lab work
find our the factorial of number using while loop
prime number
MOdule DAVIS_PYTHON_

					Sequence data type
it s a collection of datatype
list ---> collection of any type of item and mutable
tuple --